### ISSUE TITLE
Implement core library

### ISSUE THREAD

**Issue by bitbrain** [MyRealityCoding/jpersis#3]
Write the core for creating mappers and invoking their functionality.
### Tasks
- [x] Create mapper invocation
- [x] Implement annotation support
- [x] Add table generation
- [x] Implement model scanning
